// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg2Z2L1AyxDmCwIezfyVeb0IbTlCZeYAk',
    appId: '1:738658674211:android:6e097ed01f06d7a1847396',
    messagingSenderId: '738658674211',
    projectId: 'multi-notes-51ed3',
    storageBucket: 'multi-notes-51ed3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDER9mwKwYMf9ItY4shjgCG1PyWDo7sSsM',
    appId: '1:738658674211:ios:2175b2c9541311bb847396',
    messagingSenderId: '738658674211',
    projectId: 'multi-notes-51ed3',
    storageBucket: 'multi-notes-51ed3.appspot.com',
    iosClientId: '738658674211-6s0ecfij2m52i9qa0q057uagi7f583el.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDER9mwKwYMf9ItY4shjgCG1PyWDo7sSsM',
    appId: '1:738658674211:ios:2175b2c9541311bb847396',
    messagingSenderId: '738658674211',
    projectId: 'multi-notes-51ed3',
    storageBucket: 'multi-notes-51ed3.appspot.com',
    iosClientId: '738658674211-6s0ecfij2m52i9qa0q057uagi7f583el.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD6KlP2H1y0XgvDjLmdw3Zeaw59OIxnt8',
    appId: '1:738658674211:web:b04931ac2c88a361847396',
    messagingSenderId: '738658674211',
    projectId: 'multi-notes-51ed3',
    authDomain: 'multi-notes-51ed3.firebaseapp.com',
    storageBucket: 'multi-notes-51ed3.appspot.com',
    measurementId: 'G-Z3DZ34YSJC',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAD6KlP2H1y0XgvDjLmdw3Zeaw59OIxnt8',
    appId: '1:738658674211:web:56b3205537d319ae847396',
    messagingSenderId: '738658674211',
    projectId: 'multi-notes-51ed3',
    authDomain: 'multi-notes-51ed3.firebaseapp.com',
    storageBucket: 'multi-notes-51ed3.appspot.com',
    measurementId: 'G-P8TZRKEMBL',
  );
}
